image: docker:19.03.9

#services:
#  - name: docker:19.03.9-dind
#    entrypoint: ["env", "-u", "DOCKER_HOST"]
#    command: ["dockerd-entrypoint.sh"]

#variables:
#  DOCKER_HOST: tcp://docker:2375/
#  DOCKER_DRIVER: overlay2
#  DOCKER_TLS_CERTDIR: "/certs"

#before_script:
#  - docker info

build:
  stage: build
  script:
    - docker build -t codesatori_frontend
    - docker run codesatori_frontend 
    #- docker run -p80:5000 codesatori_frontend