variables:
  VM_DEPLOYMENT_PORT: "5000"
  TIME_TO_LIVE_IN_SECONDS: "180"

stages:
  - build
  - deploy-vm
  - deploy-heroku

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build --target BUILD -t codesatori-frontend .
    - docker run codesatori-frontend

deploy-vm:
  stage: deploy-vm
  script:
    - export PORT=$VM_DEPLOYMENT_PORT
    - docker build --target RUN -t codesatori-frontend .
    - timeout $TIME_TO_LIVE_IN_SECONDS docker run codesatori-frontend

deploy-heroku:
  stage: deploy-heroku
  only:
    - master
  script:
    - dpl --provider=heroku --app=codesatori --api-key=$HEROKU_API_KEY