variables:
  VM_IP: "146.169.41.91:4418"
  VM_DEPLOYMENT_PORT: "5000"
  TIME_TO_LIVE_IN_SECONDS: "90"

stages:
  - build
  - deploy-vm
  - deploy-heroku

before_script:
  - docker info
  - echo "$FIREBASE_KEYS" > ".env"

after_script:
  - docker system prune -f --all

build:
  stage: build
  script:
    - docker build --target BUILD -t codesatori-frontend .
    - docker run --env REACT_APP_CODESATORI_PROD=true codesatori-frontend

deploy-vm:
  stage: deploy-vm
  script:
    - docker build --target RUN -t codesatori-frontend .
    - timeout --preserve-status "$TIME_TO_LIVE_IN_SECONDS" docker run --env REACT_APP_CODESATORI_PROD=true -p "$VM_IP":"$VM_DEPLOYMENT_PORT" codesatori-frontend

deploy-heroku:
  stage: deploy-heroku
  only:
    - master
  script:
    - dpl --provider=heroku --app=codesatori --api-key=$HEROKU_API_KEY --skip_cleanup